### ISSUE TITLE
No device options visibleon USB Dongle (ZWave Plus USB Dongle)

### ISSUE THREAD

**Issue by SystemFuchs** [robertsLando/Zwave2Mqtt#1]
Hi there, great work! I've checked the git version yesterday with a ZWave Plus USB Dongle.
The device is recognized & after about 15 minutes all known ZWave devices appear in the webinterface.

When I select the USB Dongle there a no options under user, config, etc. So I'm not able to add devices, remove devices, etc

**Comment by robertsLando** [comment]
Try with my last commit c8c3ae28a6fec0b35fee85900a74e54d0fa5d1b7 . 

I have added 2 new functions to controller `Add Node` and `Remove node`. You find them in Control Panel in the top right corner there is a select input with a list of action that you can send to the controller.
Let me know :smile:

**Comment by SystemFuchs** [comment]
@robertsLando Thx for your quick answer 👍  , I'll give it  a try. Have to look for a timeslot because I only have one working home automation and it's offline when I'm testing your solution :-D

**Comment by robertsLando** [comment]
No worries, waiting for your feedback so I can close this issue :smile:

**Comment by robertsLando** [comment]
@SystemFuchs any updates?

**Comment by SystemFuchs** [comment]
@robertsLando Sorry, no updates until now. I hope that I'll get a timeslot this week to test it again. Did not forget it 👍

**Comment by SystemFuchs** [comment]
> @SystemFuchs any updates?

@robertsLando Inclusion and exclusion of non secure device could successfully be done.
What is not working at the moment is my danalock, which is already paired with the network key.

I've excluded the device but cannot include it secured as it seems...

**Comment by robertsLando** [comment]
I never worked with secured devices, I can't give you any help about this, if you find a solution on openzwave docs I can fix it in my code but the only thing I can do with secured devices is to set the network key on the driver on boot

**Comment by robertsLando** [comment]
@SystemFuchs try to check here: https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW

**Comment by robertsLando** [comment]
@SystemFuchs I think you shoul exclude your danalock from the controller (remove node), factory reset your danalock than add it to the controller again.

**Comment by SystemFuchs** [comment]
@robertsLando I've excluded & included it. Did not work. The only thing I've not done is the factory reset because that would have locked out my wife yesterday evening :-D 

After fiddling with the lock with openzwave I had to exclude & include it in openhab2 again & it worked. 
I'll give it another try next week because I want to use nodered with your solution to be completely independent from openhab2 and its bindings.

**Comment by robertsLando** [comment]
@SystemFuchs I'm sorry but Openzwave library doesn't give lot informations about secured devices and I really have no idea on how it works in the "low level". I think It works like https protocol and informations are encrypted using the network key but this is just a thought. I think that once you have included your danalock with openhab it may be bound with openhab zwave library (I don't know if they use openzwave) so the only thing you could try is to factory reset it (remember to exclude it from the network before or you will not able to do it later) than add it again as I said in previous post. 

Let me know if this fixes your problem, if not you should try to enable logging in zwave settings and submit here the full log trace so I can check what is going on in the low layer.

Last thing: I would like this project to grow fast so I can have more testers and fix any bug or add any feature if someone needs one so If you post in forums like openhab/home assistant node-red or everything else I would really appreciate if you share a link to this project :smiley:  

Thanks
