### ISSUE TITLE
Battery Level reported incorrectly in UI and MQTT messages

### ISSUE THREAD

**Issue by sjorge** [robertsLando/Zwave2Mqtt#13]
```xml
<CommandClass id="128" name="COMMAND_CLASS_BATTERY" version="1" request_flags="4" innif="true">
    <Instance index="1" />
    <Value type="byte" genre="user" instance="1" index="0" label="Battery Level" units="%" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="100" />
</CommandClass>
```

One of my devices is battery powered and is zwave2mqtt is getting an incorrect `Battery Level` reading from `COMMAND_CLASS_BATTERY`.

On OpenHAB the device reads 100% with 2 fresh batteries and 50% with just one battery plugged in.

For zwave2mqtt the value is displayed as '0' in the interface and on the MQTT messages. When checking zwcfg.xml (because it also saves current values) it properly has the value set 100.

**Comment by robertsLando** [comment]
Are you able to debug a nodejs project? 

You should try to lanch the application using `node --inspect bin/www` and open the link from console output and set some breakpoints in `lib/ZwaveClient.js` on lines 231-242. There you can detect when a value is added or it changes and see if there is a parse error there, I can't reproduce your problem with my devices

**Comment by sjorge** [comment]
I've not done so before, but I can give this a try later this week. Probably on wednesday as I should be home ealier from work then.

**Comment by robertsLando** [comment]
Ok @sjorge let me know if you need help :smiley:  thanks !

**Comment by robertsLando** [comment]
Follow this guide to check how to debug nodejs app step by step using chrome: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by sjorge** [comment]
Doesn't look like this works for a remote application? Well I got the inspector to attach but the sources tab is empty.

**Comment by sjorge** [comment]
Not ideal but I inserted debug(valueId); so I should get some data when the device checks in.

**Comment by sjorge** [comment]
```
  z2m:Zwave { value_id: '2-128-1-0',
  z2m:Zwave   node_id: 2,
  z2m:Zwave   class_id: 128,
  z2m:Zwave   type: 'byte',
  z2m:Zwave   genre: 'user',
  z2m:Zwave   instance: 1,
  z2m:Zwave   index: 0,
  z2m:Zwave   label: 'Battery Level',
  z2m:Zwave   units: '%',
  z2m:Zwave   help: '',
  z2m:Zwave   read_only: true,
  z2m:Zwave   write_only: false,
  z2m:Zwave   min: 0,
  z2m:Zwave   max: 255,
  z2m:Zwave   is_polled: false,
  z2m:Zwave   value: 0 } +1ms
  z2m:Zwave ValueAdded: 2-128-1-0 Battery Level +0ms
```

Very interesting, it might be a openzwave bug then? Although a value of byte for battery level seems a bit weird too.

**Comment by robertsLando** [comment]
For the debug: you need to install chrome nodejs inspector plugin from chrome webstore. 

About the probelm: I think is something related to the Openzwave library or (more likely) something wrong in the device xml configuration (that you can also find in openzwave github under [/config](https://github.com/OpenZWave/open-zwave/tree/master/config) folder). 
Try to rise an issue or try to check in other battery powered devices configuration xml how they manage that kind of command class value. 

Let me know



Daniel

**Comment by sjorge** [comment]
I was googling on my phone but cannot locate the link anymore, but I found something about COMMAND_CLASS_BATTERY needs to be polled to get an update. As device only send it when the value changes.

Is there a way to send a poll request to see if it will update?

**Comment by sjorge** [comment]
I removed both batteries, waited for 5 minutes and inserted one battery.
At the next interval it reported a battery level of 50.

Repeat but with 2 batteries, we are now back to 100. 
I'm going to close this.

**Comment by robertsLando** [comment]
To poll a value you can use the Gateway values table on UI settings tab, you just have to select the device and the value and set the pool to true (leave topic blank to keep the default topic or choose one to override it), in this way on init I will automatically poll all nodes of that product type; otherwise you can manually enable the poll of that value (but you need to do it for each node) using the mqtt api `enablePoll(valueId, intensity)`, remember that if you use the second option you need to enable poll on every init 

Daniel

**Comment by sjorge** [comment]
Good to know, but it now seems to be updating and I did not do anything with the polling, it might just have been in a weird state because I was messing with it a bit too much.
