### ISSUE TITLE
How to access second channel on multi-zoned thermostat?

### ISSUE THREAD

**Issue by tul** [robertsLando/Zwave2Mqtt#15]
Hi,

I have a "SSR 302 2-zone Thermostat Receiver (Horstmann (Secure Meters))" (https://www.vesternet.com/mwdownloads/download/link/id/517/) which exposes two channels to switch on either the central heating or the hot water cylinder.

If I switch the "Mode" of value `3-64-2-0` using the web UI of Zwave2Mqtt, I see the following on the MQTT bus:

    zwave/utility/heating/thermostat_mode/mode {"value_id":"3-64-2-0","node_id":3,"class_id":64,"type":"list","genre":"user","instance":2,"index":0,"label":"Mode","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Off","Heat"],"value":"Heat"}

And the 2nd channel of the thermostat activates as expected.

How can I use the gateway to toggle this? I have tried:

    mosquitto_pub -t zwave/utility/heating/thermostat_mode/mode/set -m '{"value_id":"3-64-2-0","node_id":3,"class_id":64,"type":"list","genre":"user","instance":2,"index":0,"label":"Mode","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Off","Heat"],"value":"Heat"}'

But for some reason - that actually toggles channel 1 and not channel 2, resulting in the following output on the MQTT bus:

    zwave/utility/heating/thermostat_mode/mode/set {"value_id":"3-64-2-0","node_id":3,"class_id":64,"type":"list","genre":"user","instance":2,"index":0,"label":"Mode","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Off","Heat"],"value":"Heat"}
    zwave/utility/heating/thermostat_mode/mode {"value_id":"3-64-1-0","node_id":3,"class_id":64,"type":"list","genre":"user","instance":1,"index":0,"label":"Mode","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Off","Heat"],"value":"Heat"}

Note above, the value_id being set is `3-64-2-0` but the value being altered is `3-64-1-0` (i.e. the other channel).

Am I sending the wrong command to the MQTT gateway here?

**Comment by tul** [comment]
I've investigate a little, and the issue seems to be in `Gateway.js` here:

```
function onWriteRequest(parts, payload){
  var value = this.topicValues[parts.join('/')];

  if(value){
    payload = parsePayload(payload, value, value.conf, this.config)
    this.zwave.writeValue(value, payload);
  }
}
```

It seems that for the topic (`utility/heating/thermostat_mode/mode` in this case) only one value is stored, the value for channel 1. So when setting channel 2, it is being routed to channel 1.

Could it be that the gateway only supports one value per topic currently?

**Comment by tul** [comment]
I am still quite new to ZWave, however I'm happy to look at creating a PR to resolve this issue if the maintainers could offer me a little guidance on their preferred approach.

**Comment by tul** [comment]
As a workaround, I have realised I can do

    mosquitto_pub -t zwave/_CLIENTS/ZWAVE_GATEWAY-fluoron/api/setValue/set -m '{"args":[ { "node_id": 3, "class_id": 64, "instance": 1, "index": 0 }, "Heat" ] }'

and

    mosquitto_pub -t zwave/_CLIENTS/ZWAVE_GATEWAY-fluoron/api/setValue/set -m '{"args":[ { "node_id": 3, "class_id": 64, "instance": 2, "index": 0 }, "Heat" ] }'

to control the two channels independently.

**Comment by robertsLando** [comment]
Hi @tul, thanks for your issue!

> It seems that for the topic (utility/heating/thermostat_mode/mode in this case) only one value is stored in the this.topicValues which is the value for channel 1. So when setting channel 2, it is being routed to channel 1.

This is correct and sincerly I will try to fix this. As workaround you can send a raw api request like you did or add two values on gateway values tables (Go to the web UI under Settings at the end and click on `new value`. Here you can select values from devices and choose a custom topic for them :)

**Comment by robertsLando** [comment]
@tul Could you check it it works now? :smiley: I have also updated Readme: 

  2. **Named Topics**: *Automatically configured*. The topic where zwave values are published will be:

  `<mqtt_prefix>/<?node_location>/<node_name>/<class_name>/<?instance>/<value_label>`

    - `mqtt_prefix`: the prefix set in Mqtt Settings
    - `node_location`: location of the Zwave Node (optional, if not present will not be added to the topic)
    - `node_name`: name of the node, if not set will be `nodeID_<node_id>`
    - `class_name`: the node class name corrisponding to given class id or `unknownClass_<class_id>` if the class name is not found
    - `?instance`: Used just with multi-instance devices. The main instance (1) will not have this part in the topic but other instances will have: `instance_<instance_index>`
    - `value_label`: the zwave value label (lower case and spaces are replaced with `_`)

**Comment by tul** [comment]
Hi @robertsLando - yes your fix has worked great, thanks very much for the quick response!

**Comment by tul** [comment]
For those finding this issue, the new pub call after the fix is now:

    mosquitto_pub -t zwave/utility/heating/thermostat_mode/instance_2/mode/set -m '{"value_id":"3-64-2-0","node_id":3,"class_id":64,"type":"list","genre":"user","instance":2,"index":0,"label":"Mode","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Off","Heat"],"value":"Heat"}'
