### ISSUE TITLE
Label also has value for node name and location

### ISSUE THREAD

**Issue by sjorge** [robertsLando/Zwave2Mqtt#16]
![screenshot](https://i.imgur.com/yGVHrji.png)

Seems a bit silly to repeat the value twice

**Comment by robertsLando** [comment]
The value is different because on the left you have the actual value (that you can't modify) and on the right an input text with the new value to set (that is equal to the actual value as default), if you edit it you can alway check the old one instead of scroll up and check in the table.

**Comment by sjorge** [comment]
OK so a feature then.
