### ISSUE TITLE
Request - Node Location

### ISSUE THREAD

**Issue by gazoscalvertos** [robertsLando/Zwave2Mqtt#3]
Hi,

Wondering whether a button to disable showing node_location in the topic even when present?

I like the node_location feature however if zwave2mqtt restarts then it needs to wait until the devices have woken up and synced it's status before it picks up the location again. Or maybe I'm missing something?

I have this running in docker so maybe there are persistent files I need to look out for.

Thanks

**Comment by robertsLando** [comment]
Why don't simply set node location to "" (empty string)? Anyway, node location and node name properties are stored in `zwcfg_<homeIdhex>.xml` file, those properties are loaded once node is ready

**Comment by gazoscalvertos** [comment]
Yeah I realise not setting a value works it was more for the aesthetics. My sensors are battery powered so only report as ready once they have woken up and synced if the system has been restarted, if the sensor is tripped in the meantime they would report this immediately and this would display as the nodeid rather than the name which is fine as I can work with nodeIDs.

I'll add in the button on my setup and see how it goes.

Thanks for the response.

**Comment by robertsLando** [comment]
@gazoscalvertos  I usually use only AC powered devices so I didn't know about this. I know there is an option in zwave options called `AssumeAwake` : 

> Assume Devices that support the Wakeup Class are awake when starting up OZW

Maybe this option could help you?

**Comment by gazoscalvertos** [comment]
Thanks, I will check this out!

**Comment by SystemFuchs** [comment]
> @gazoscalvertos I usually use only AC powered devices so I didn't know about this. I know there is an option in zwave options called `AssumeAwake` :
> 
> > Assume Devices that support the Wakeup Class are awake when starting up OZW
> 
> Maybe this option could help you?

How do I set this option? I've got about 1/3 of battery driven devices?

**Comment by robertsLando** [comment]
Sorry for the late replay, I have made some updates in last commit 1840bef82ae786fd2adf6becb99619950cb5e356 .

Now nodes name and location are loaded on driver ready so this fix your problem @gazoscalvertos . 
Now you can also specify a custom config path (devices xml config database) 

I will add the option `AssumeAwake` in next commit give me some minutes

**Comment by robertsLando** [comment]
`AssumeAwake` option added with 88698bdc1d7f77c7d8d256b829b69c85f1b2b58c

Pull the new version and let meknow @SystemFuchs  @gazoscalvertos

**Comment by gazoscalvertos** [comment]
Awesome thanks @robertsLando !!! Will check this out and get back to you

**Comment by gazoscalvertos** [comment]
I can confirm this is working great, Operating on a docker container hosted by a RPI3

**Comment by robertsLando** [comment]
@gazoscalvertos could you kindly submit a pull request with the Dockerfile you have used to create your docker container? It is in my todo list :)

**Comment by gazoscalvertos** [comment]
Yeah no problem, I'm trying to finesse it slightly as the image size is 600MB. It builds everything from source as to pull the latest version of open-zwave

**Comment by robertsLando** [comment]
You can both create the container using the pkg version (so you don't need to install nodejs too) or the entire nodejs app. 
The first requires you to build the app using pkg (check dev section on readme) for the second I think you know as I think it is what you did :)
