### ISSUE TITLE
Settings does not load settings after a restart (on SmartOS/FreeBSD)

### ISSUE THREAD

**Issue by sjorge** [robertsLando/Zwave2Mqtt#6]
```Error while retriving configuration, check console ```

Is displayed for a few seconds on the popup at the bottom.

```
  z2m:App Error: spawn udevadm ENOENT
  z2m:App     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
  z2m:App     at onErrorNT (internal/child_process.js:362:16)
  z2m:App     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  z2m:App     at process._tickCallback (internal/process/next_tick.js:181:9) +215ms
```

That might be to blame.

**Comment by sjorge** [comment]
I did some digging while I had a few minutes, looks like this is comming from the serialport library, seems it works fine for all the read/write stuff just not the listing stuff on non linux/mac.

On first run I can configure it by entering the path and everything keeps working, so It's a bit odd that it would error out only when a port has been entered already. I wonder if simply making this non fatal would work.

**Comment by robertsLando** [comment]
Hi @sjorge, Thanks again for the issue, every feedback is useful for me? :) I have just commited a possible fix to your problem, please let me know if your problem is fixed now

**Comment by sjorge** [comment]
Hi @robertsLando with that fix applied everything looks to be working fine now!
I'll give this a more better shake down this weekend when I try and convert my node-red setup from openhab as input to zwave2mqtt as input, small scale testing looks extremely promising. I should also have an extra device by then so I can test the inclusion commands also.

**Comment by robertsLando** [comment]
Perfect! Waiting for your feedback and thanks again 🙏🏻
