### ISSUE TITLE
[Bug] Menu always expands on click

### ISSUE THREAD

**Issue by sjorge** [robertsLando/Zwave2Mqtt#8]
You can collapse the menu by clicking on the little 3 strip icon in the header.
This is great if the screen space available is small (say a small tablet), tapping a menu icon will expand the menu again. 

Ideally it should remain collapsed until the header is clicked again.

**Comment by robertsLando** [comment]
Will sort this out tomorrow morning. Thanks :)

**Comment by robertsLando** [comment]
@sjorge please let me know if now everything works as expected 😊

**Comment by sjorge** [comment]
Works perfectly! I'll let you know how the conversion from OpenHAB goes this weekend, some brief tests shows everything arriving fine but it will take a few hours to convert all home flows.

**Comment by robertsLando** [comment]
Let me know @sjorge! Every feedback is more than welcome 😊 oh and if you find some topic about openzwave in openhab forum or any other forum share a link to this project so I can have many other testers to improve it! 



Daniel
