### ISSUE TITLE
UI Toggle buttons (for Switches) does a weird state dance when toggled

### ISSUE THREAD

**Issue by sjorge** [robertsLando/Zwave2Mqtt#9]
I have a outlet device that has an on/off switch exposed in the user settings.

Changing the stay from On -> Off (or Off -> On) will make the toggle switch position, but immediately go back to the previous position. (It also sends the zwave command to the device). The device them responds with the new state making the toggle go to the correct state.

It would be nice that the button stays at the new position and maybe is disabled for a second (or until a new update is received - which ever comes first I guess).

**Comment by sjorge** [comment]
This is probably related to #12

**Comment by robertsLando** [comment]
This is the switch: 

```vue
  <v-switch
      v-if="value.type == 'bool'"
      :label="value.label +' ('+value.value_id+')'"
      :hint="value.help || ''"
      persistent-hint
      v-model="value.newValue"
      @change="updateValue(value)"
      ></v-switch>
```
Each valueID object is bounded to an input element (like text input, select, number input etc..) and it must be bounded to a var, in this case I have bound it `valueID.newValue`. What happens in your case is correct even if it seems weird:

You press the switch and the switch changes state as feedback that you have pressed it,
For some reason before the value update is triggered you receive another update that puts the switch to the previous state than you receive the new update and the switch takes the correct state.

I can't disable the position for some seconds as I can't compare the two state changes and decide which one (the first or the second) is the correct one. If you check the source code and you have an idea about how to fix this let me know

**Comment by sjorge** [comment]
So it is related to #12 then, I'll close this one then.

**Comment by sjorge** [comment]
Just letting you know It's been running perfectly for a few weeks now!

**Comment by robertsLando** [comment]
Perfect 👌🏻
